name: emusic
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  esewa_pnp: ^2.0.0
  cupertino_icons: ^1.0.2
  get: 4.6.1
  google_fonts: ^2.3.1
  firebase_storage: ^10.2.10
  firebase_core: ^1.14.0
  audioplayers: ^0.20.1
  fluttertoast: ^8.0.9
  flutter:
    sdk: flutter
  cloud_firestore: ^3.1.11
  google_sign_in: ^5.2.4
  image_picker: ^0.8.4+11
  file_picker: ^4.5.1
  path: ^1.8.0
  share_plus: ^4.0.3
  path_provider: ^2.0.9
  permission_handler: ^9.2.0
  flutter_downloader: ^1.7.3
  http: ^0.13.4
  

  
dev_dependencies:
  flutter_lints: ^1.0.0
  lints: 1.0.1
  flutter_screenutil: ^5.3.1
  font_awesome_flutter: ^10.0.0
  firebase_auth: ^3.3.12
  flutter_launcher_icons: ^0.9.2
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/esewa/
